<a href="https://colab.research.google.com/github/Fizza111/Next-word-prediction-using-RNN-and-LSTM/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
sentences=[
     "Machine learning is transforming how we interact with technology every day."
     "Algorithms learn from data to make predictions or decisions."
     "Supervised learning teaches models using labeled examples."
     "Unsupervised learning uncovers hidden patterns in data without labels."
     "Reinforcement learning mimics reward-based behavior like training a pet."
     "The more data, the better the model usually performs."
     "Neural networks mimic the way human brains process information."
     "Feature engineering is the art of selecting relevant input variables."
     "Bias in training data can lead to unfair predictions."
     "Machine learning powers everything from spam filters to self-driving cars."
     "Overfitting happens when a model learns noise instead of signal."
     "Underfitting means the model isn’t learning enough from the data."
     "Training data is the foundation of any machine learning model."
     "Hyperparameters control how a model learns."
     "Classification assigns categories, while regression predicts values."
     "Data preprocessing cleans and transforms raw data for modeling."
     "Cross-validation helps evaluate model performance reliably."
     "Gradient descent helps optimize the model's accuracy."
     "Decision trees are easy to understand but prone to overfitting."
     "Support vector machines find the optimal boundary between classes."
     "Deep learning leverages multiple layers of abstraction."
     "Machine learning models can improve over time with new data."
     "Label imbalance can skew prediction results."
     "Scikit-learn is a popular Python library for ML."
     "TensorFlow and PyTorch are widely used for deep learning."
     "Model accuracy isn’t always enough; interpretability matters too."
     "AI applications often use machine learning at their core."
     "Linear regression is one of the simplest ML techniques."
     "Clustering groups similar data points together."
     "K-means is a popular clustering algorithm."
     "Ensemble methods combine predictions from multiple models."
     "Random Forest is a type of ensemble method using decision trees."
     "A confusion matrix helps visualize classification performance."
     "Precision and recall balance correctness and completeness."
     "F1 score provides a single metric for classification trade-offs."
     "Machine learning is reshaping medicine, finance, and retail."
     "Predictive modeling enables proactive decision-making."
     "Anomaly detection spots unusual data points."
     "Sentiment analysis can reveal customer opinions automatically."
     "Spam filters use machine learning to sort unwanted emails."
     "Image recognition is driven by convolutional neural networks."
     "Transfer learning reuses knowledge from previous models."
     "ML models need fine-tuning to reach optimal performance."
     "Ethical use of machine learning is a growing concern."
     "Explainable AI helps build trust in model predictions."
     "Automated ML tools simplify the training process."
     "Time series models forecast trends and patterns over time."
     "Data labeling can be expensive and time-consuming."
     "Machine learning is evolving rapidly with new innovations."
     "Training a model can take minutes or weeks, depending on complexity."
     "Model deployment brings ML models to real-world applications."
     "Streaming data requires online learning methods."
     "Feature selection reduces dimensionality and noise."
     "Dimensionality reduction simplifies data without losing insights."
     "Principal Component Analysis is a technique for reducing data dimensions."
     "Machine learning thrives in environments rich in feedback."
     "Computational power is critical for training complex models."
     "GPU acceleration speeds up deep learning tasks."
     "Hyperparameter tuning boosts model performance."
     "Automated pipelines help streamline ML workflows."
     "Data visualization helps interpret model outputs."
     "Categorical variables often require encoding techniques."
     "Normalization makes features comparable across scales."
     "Overlapping classes complicate classification problems."
     "Natural Language Processing is powered by machine learning."
      "Data augmentation improves model generalization."
      "Reproducibility in ML ensures consistent results."
      "Machine learning models must be monitored after deployment."
      "Model drift occurs when data changes over time."
      "Online learning adapts to incoming data in real time."
      "Cloud platforms offer scalable ML training environments."
      "Real-time prediction is critical in applications like fraud detection."
      "Reinforcement learning can outperform humans in games."
      "ML models often require continuous evaluation."
      "Algorithms vary widely in complexity and purpose."
      "Training data should reflect the problem space accurately."
      "Bias-variance tradeoff affects model generalization."
      "Bagging and boosting are techniques to improve accuracy."
      "Model checkpoints save training progress."
      "Early stopping prevents overfitting during training."
      "Loss functions quantify prediction errors."
      "Optimization algorithms search for the best model parameters."
      "Ethical datasets avoid reinforcing harmful stereotypes."
      "Human oversight in ML helps maintain responsibility."
      "Neural architecture search automates model design."
      "Machine learning enhances recommendation systems."
      "Dynamic pricing uses ML to adjust prices on demand."
      "Voice assistants rely on machine learning for understanding speech."
      "Facial recognition uses deep learning to identify individuals."
      "Generative models can create realistic images and sounds."
      "Machine learning isn’t magic—it’s mathematics at scale."
      "Collaborative filtering predicts user preferences."
      "Data scientists work closely with ML models."
      "ML-based robotics can adapt to changing environments."
      "Health diagnostics benefit from intelligent predictions."
      "Fraud detection systems rely heavily on ML signals."
      "Self-driving cars constantly learn from their surroundings."
      "Personalization engines recommend content or products."
      "Social media feeds are shaped by ML algorithms."
      "Human-in-the-loop approaches combine ML and expert input."
      "Zero-shot learning makes predictions on unseen categories."
      "Few-shot learning trains with very little labeled data."
      "Active learning queries the user for uncertain cases."
      "Meta-learning teaches models how to learn better."
      "Machine learning is the heartbeat of modern AI systems."
      "With data and algorithms, machine learning unlocks new frontiers."
]

In [6]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(sentences)
total_words=len(tokenizer.word_index) + 1
print(total_words)
print(tokenizer.word_index)
input_sequences=[]
for line in sentences:
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequences=token_list[:i+1]
        input_sequences.append(n_gram_sequences)
max_sequence_length=max([len(x) for x in input_sequences])
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_length,padding="pre"))
print(input_sequences)

447
{'learning': 1, 'data': 2, 'model': 3, 'machine': 4, 'the': 5, 'is': 6, 'ml': 7, 'to': 8, 'models': 9, 'and': 10, 'in': 11, 'a': 12, 'training': 13, 'can': 14, 'for': 15, 'of': 16, 'from': 17, 'time': 18, 'with': 19, 'predictions': 20, 'helps': 21, 'algorithms': 22, 'on': 23, 'learn': 24, 'classification': 25, 'performance': 26, 'are': 27, 'deep': 28, 'how': 29, 'or': 30, 'neural': 31, 'human': 32, 'overfitting': 33, 'isn’t': 34, 'accuracy': 35, 'decision': 36, 'over': 37, 'new': 38, 'prediction': 39, 'ai': 40, 'applications': 41, 'often': 42, 'use': 43, 'techniques': 44, 'detection': 45, 'by': 46, 'real': 47, 'environments': 48, 'systems': 49, 'teaches': 50, 'using': 51, 'labeled': 52, 'patterns': 53, 'without': 54, 'reinforcement': 55, 'based': 56, 'like': 57, 'better': 58, 'networks': 59, 'process': 60, 'feature': 61, 'input': 62, 'variables': 63, 'bias': 64, 'spam': 65, 'filters': 66, 'self': 67, 'driving': 68, 'cars': 69, 'when': 70, 'learns': 71, 'noise': 72, 'means': 73, 'en

In [14]:
#split data into input and labels
X=input_sequences[:, :-1]
print("input data :",X)
y=input_sequences[: ,-1]
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
#Structurs of RNN model
model=Sequential([
    Embedding(total_words,10,input_length=max_sequence_length-1),
    SimpleRNN(100),
    Dense(total_words,activation="softmax")

])

input data : [[  0   0   0 ...   0   0   4]
 [  0   0   0 ...   0   4   1]
 [  0   0   0 ...   4   1   6]
 ...
 [  0   0   4 ...  22   4   1]
 [  0   4   1 ...   4   1 445]
 [  4   1   6 ...   1 445  38]]


In [15]:
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])

In [16]:
model.fit(X,y,epochs=70,verbose=1)

Epoch 1/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - accuracy: 0.0014 - loss: 6.1067
Epoch 2/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.0049 - loss: 6.0846
Epoch 3/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.0256 - loss: 5.9225
Epoch 4/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.0357 - loss: 5.6726
Epoch 5/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.0310 - loss: 5.6376
Epoch 6/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.0408 - loss: 5.6096
Epoch 7/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.0379 - loss: 5.6003
Epoch 8/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.0421 - loss: 5.6292
Epoch 9/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - accuracy: 0.0331 - loss: 5.5814
Epoch 10/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.0354 - loss: 5.4971
Epoch 11/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 0.0406 - loss: 5.5942
Epoch 12/70
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy:

In [24]:
def predict_next_word(seed_text, next_words=3):
    for _ in range(next_words):  # fixed variable name from 'next_word' to 'next_words'
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_length - 1)
        predicted = model.predict(token_list, verbose=0)
        predicted_word_index = np.argmax(predicted, axis=-1)[0]
        predicted_word = tokenizer.index_word[predicted_word_index]
        seed_text += " " + predicted_word

    return seed_text

In [33]:
print(predict_next_word("I am a data scientist and noise dimensionality and noise dimensionality reduction and simplifies data without data"))

I am a data scientist and noise dimensionality and noise dimensionality reduction and simplifies data without data without losing insights
